package com.collegefiles.app.sync

import android.net.Uri
import android.provider.OpenableColumns
import android.content.Context
import com.collegefiles.app.upload.UploadManager

sealed class ShareResolveResult {
    data class MatchFound(val session: DocumentSession) : ShareResolveResult()
    data class NoMatch(val fileName: String) : ShareResolveResult()
}

class ShareImportManager(
    private val context: Context,
    private val repository: DocumentSessionRepository
) {
    fun resolveSession(uri: Uri): ShareResolveResult {
        val fileName = getFileName(context, uri)
        
        // The file name generated by DocumentSessionService has format: {shortUUID}_filename.ext
        // We look for a session that has a matching prefix.
        val activeSessions = repository.sessions.value.values.filter { 
            it.state != SessionState.FAILED && it.state != SessionState.COMPLETED
        }
        
        for (session in activeSessions) {
            val shortId = session.sessionId.toString().substring(0, 8)
            if (fileName.contains(shortId, ignoreCase = true)) {
                return ShareResolveResult.MatchFound(session)
            }
        }
        
        // Fallback exact match on localFile name
        for (session in activeSessions) {
            if (session.localFile.name == fileName) {
                return ShareResolveResult.MatchFound(session)
            }
        }
        
        return ShareResolveResult.NoMatch(fileName)
    }

    private fun getFileName(context: Context, uri: Uri): String {
        var result: String? = null
        if (uri.scheme == "content") {
            context.contentResolver.query(uri, null, null, null, null)?.use { cursor ->
                if (cursor.moveToFirst()) {
                    val index = cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME)
                    if (index != -1) {
                        result = cursor.getString(index)
                    }
                }
            }
        }
        if (result == null) {
            result = uri.path
            val cut = result?.lastIndexOf('/') ?: -1
            if (cut != -1) {
                result = result?.substring(cut + 1)
            }
        }
        return result ?: "upload"
    }
}
